### ISSUE TITLE
surport  z3 4.8.14.0 

### ISSUE THREAD

**Issue by xunforce** [CERTCC/kaiju#16]
**Is your feature request related to a problem? Please describe.**
This problem is about build.

**Describe the solution you'd like**
support z3 4.8.14.0 

**Describe alternatives you've considered**
IDA

**Additional context**

**Comment by xunforce** [comment]
a part of log:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':copyToLib'.
> Could not resolve all files for configuration ':z3Dependency'.
   > Could not find :com.microsoft.z3:4.8.11.0.
     Searched in the following locations:
       - file:/D:/git/kaiju/lib/com.microsoft.z3.jar/com.microsoft.z3-4.8.11.0.jar
       - file:/D:/git/kaiju/lib/com.microsoft.z3.jar/com.microsoft.z3.jar
     Required by:
         project :

**Comment by sei-eschwartz** [comment]
It's not immediately clear to me how we can support a range of z3 versions because of the `copyToLib` target, but this is something we should look into.

For the moment, you should be able to find a replace 4.8.11.0 to 4.8.14.0 and I think it should work fine.

**Comment by gwasser** [comment]
It should support any version of z3 (at least if the API didn't majorly change!) because gradle looks for a non-versioned z3 jar file, check out this line:

`file:/D:/git/kaiju/lib/com.microsoft.z3.jar/com.microsoft.z3.jar`

So you need to point gradle at the folder where the `com.microsoft.z3.jar` file lives on your system. I believe you should have this file if you built z3 yourself, but I also haven't tried this much on Windows so please let us know if you have problems!

To tell gradle where to search for this file, you can use:
`gradle -PZ3CLASSPATH=<Absolute path to dir with Z3 .jar file>`

**Comment by sei-gwassermann** [comment]
Did this work @xunforce? I will close this ticket for now but please let us know if you still have any questions or issues, thanks for reporting!
